### ISSUE TITLE
"Fork me on github" banner

### ISSUE THREAD

**Issue by austinwk** [austinwk/rails_workshop_website#16]
- There should be a banner in the top right corner that states "Fork me on GitHub" with the GitHub logo.
- This should be placed on `header.component.html` with styling in `header.component.scss`.
- This should not be visible on mobile.
- Clicking on the banner should open a new tab to [the repo for this project](https://github.com/austinwk/rails_workshop_website)
- You can find an example of such a banner [here](http://aral.github.com/fork-me-on-github-retina-ribbons/right-red@2x.png).

Alternatively, you can use a pre-made image as provided in this blog post: https://github.blog/2008-12-19-github-ribbons/

**Comment by kacollins** [comment]
Done in 2508569.
