### ISSUE TITLE
Add Moonswitch to Sponsors

### ISSUE THREAD

**Issue by kacollins** [austinwk/rails_workshop_website#23]
![](https://moonswitch.com/wp-content/uploads/2018/03/logo-sideways-large-text.png)

**Comment by jeff-french** [comment]
Here's one that's 800px x 330px. 

![logo sideways large text 0 25x](https://user-images.githubusercontent.com/209994/52582671-5b164600-2df3-11e9-9112-06f4c4bb80b1.png)

And 1056px x 435px

![logo sideways large text 0 33x](https://user-images.githubusercontent.com/209994/52582737-7e40f580-2df3-11e9-86c0-2ccdbbde2579.png)

And 2400px x 990px

![logo sideways large text 0 75x](https://user-images.githubusercontent.com/209994/52582752-8c8f1180-2df3-11e9-9202-5e552d39b806.png)
